# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib foresightr, .registration = TRUE
NULL

#' Name and description of a model specification.
#' @noRd
rs_model_label <- function(spec) .Call(wrap__rs_model_label, spec)

#' Fits a model; returns what was estimated and a pointer for forecasting.
#' @noRd
rs_fit <- function(spec, values, period, phase) .Call(wrap__rs_fit, spec, values, period, phase)

#' Forecasts from a fit.
#' @noRd
rs_predict <- function(pointer, h) .Call(wrap__rs_predict, pointer, h)

#' Fits and forecasts in one go.
#' @noRd
rs_forecast <- function(spec, values, period, phase, h) .Call(wrap__rs_forecast, spec, values, period, phase, h)

#' Runs a backtest.
#' @noRd
rs_backtest <- function(values, period, phase, candidates, origins, horizon, min_train, window, combine, levels, metric, parallel) .Call(wrap__rs_backtest, values, period, phase, candidates, origins, horizon, min_train, window, combine, levels, metric, parallel)

#' STL.
#' @noRd
rs_stl <- function(values, period, seasonal_window, trend_window, low_pass_window, degrees, robust, inner, outer) .Call(wrap__rs_stl, values, period, seasonal_window, trend_window, low_pass_window, degrees, robust, inner, outer)

#' MSTL.
#' @noRd
rs_mstl <- function(values, periods, windows, iterations, robust) .Call(wrap__rs_mstl, values, periods, windows, iterations, robust)

#' Fills gaps.
#' @noRd
rs_interpolate <- function(values, period) .Call(wrap__rs_interpolate, values, period)

#' Finds outliers (1-based positions).
#' @noRd
rs_outliers <- function(values, period) .Call(wrap__rs_outliers, values, period)

#' Fills gaps and replaces outliers.
#' @noRd
rs_clean <- function(values, period) .Call(wrap__rs_clean, values, period)

#' @noRd
rs_acf <- function(values, max_lag) .Call(wrap__rs_acf, values, max_lag)

#' @noRd
rs_kpss <- function(values) .Call(wrap__rs_kpss, values)

#' @noRd
rs_ndiffs <- function(values, max) .Call(wrap__rs_ndiffs, values, max)

#' @noRd
rs_nsdiffs <- function(values, period) .Call(wrap__rs_nsdiffs, values, period)

#' @noRd
rs_seasonal_strength <- function(values, period) .Call(wrap__rs_seasonal_strength, values, period)

#' @noRd
rs_box_cox <- function(values, lambda, inverse) .Call(wrap__rs_box_cox, values, lambda, inverse)

#' @noRd
rs_guerrero <- function(values, period, phase) .Call(wrap__rs_guerrero, values, period, phase)

#' @noRd
rs_accuracy <- function(actual, forecast, measure) .Call(wrap__rs_accuracy, actual, forecast, measure)

#' @noRd
rs_mase <- function(actual, forecast, train, period) .Call(wrap__rs_mase, actual, forecast, train, period)

#' @noRd
rs_fourier <- function(period, order, rows) .Call(wrap__rs_fourier, period, order, rows)

#' @noRd
rs_seasonal_dummies <- function(period, rows) .Call(wrap__rs_seasonal_dummies, period, rows)

# nolint end
